version: '3'
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: labuser
      POSTGRES_PASSWORD: labpassword
      POSTGRES_DB: labdb
    volumes:
      - ./db/changelog:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "labuser", "-d", "labdb"]
      interval: 5s
      timeout: 1s
      retries: 10

#  tools-gps-gen:
#      build:
#        context: .
#      environment:
#        DATABASE_URL: "host=postgres user=labuser password=labpassword dbname=labdb sslmode=disable"
#      depends_on:
#        postgres:
#          condition: service_healthy
#      command: ["go", "run", "./cmd/tools/main.go"]

  app:
    build:
      context: .
    environment:
      DATABASE_URL: "host=postgres user=labuser password=labpassword dbname=labdb sslmode=disable"
    ports:
      - "8080:8080"
    depends_on:
      postgres:
          condition: service_healthy
